name: zero2prod
region: sfo3
services:
  - name: zero2prod
    dockerfile_path: Dockerfile
    source_dir: .
    image:
        registry_type: DOCR
        repository: zero2prod
        tag: latest
    health_check:
        http_path: /health_check
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
        - path: /
# databases:
#   - engine: PG
#     name: newsletter
#     num_nodes: 1
#     size: db-s-dev-database
#     version: "12"